### ISSUE TITLE
Command failed 

### ISSUE THREAD

**Issue by Skoks** [kevva/wifi-password#2]
I get this error when I execute `wifi-password`: 

Command failed: /bin/sh: -c: line 0: unexpected EOF while looking for matching `"'
/bin/sh: -c: line 1: syntax error: unexpected end of file

**Comment by kevva** [comment]
@Skoks, OS X?

**Comment by Skoks** [comment]
@kevva Yes, Sir!

**Comment by mischah** [comment]
Same here. 
OS X 10.9.5 using the default bash.

**Comment by kevva** [comment]
@mischah, I've updated the command, could you try installing directly from the repo and try?

**Comment by anselmh** [comment]
I think related to this: 

    Command failed: sed: 1: "s/^.*"\(.*)".*$/\1/
    ": RE error: parentheses not balanced

If not related, let me know. Using `zsh` and the latest npm version of this tool.

**Comment by mischah** [comment]
Now it says:

```
Command failed: sed: 1: "s/^.*"\(.*)".*$/\1/
": RE error: parentheses not balanced
security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
```

Pretty much the same message that @anselmh mentioned before.

**Comment by kevva** [comment]
Alright, could you run `security find-generic-password -ga your-wifi-name` for me so I can have a look at the output. I think it's better to parse it using JS instead of `sed` etc.

**Comment by anselmh** [comment]
Sure:

> `security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.`

**Comment by kevva** [comment]
Are you connected to a network? Seems like you're not.

**Comment by anselmh** [comment]
Sorry, updated now. Forgot to change network name :D

**Comment by kevva** [comment]
Alright, thanks :).

**Comment by kevva** [comment]
@Skoks, @mischah, @anselmh, should be fixed now!

**Comment by Skoks** [comment]
@kevva Still not working for me... I have tried it on another Mac OS machine with `zsh`. [Screenshot](http://monosnap.com/image/cyMhUKbnb8xXop7T2959if7rX0gPrJ)

**Comment by kevva** [comment]
@Skoks, you have to install the new version globally too. You've only installed that one locally.

**Comment by Skoks** [comment]
"лу

**Comment by Skoks** [comment]
@kevva After installing it globally and running `wifi-password` Mac OS prompts for username and password (I guess it's  because I have to run `node` with `sudo`).  After providing credentials `wifi-password` outputs `null`
